export const OPEN_MENU = "OPEN_MENU"
export const GENERATE_NOTIFICATION = "GENERATE_NOTIFICATION"
export const DELETE_NOTIFICATION = "DELETE_NOTIFICATION"

export const SELECT_LANGUAGE = "SELECT_LANGUAGE"