export const GET_ALL_RESTAURANTS = "GET_ALL_RESTAURANTS"

export const SELECT_CUISINE = "SELECT_CUISINE"

export const SELECT_FILTER_ICON = "SELECT_FILTER_ICON"

export const SET_SEARCH_VALUE = "SET_SEARCH_VALUE"

